spring:
  application:
    name: "Demo Lite Java"

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    # Locale used for formatting
    time-zone: UTC

couchbase:
  remote:
    endpoint-url: wss://wazhi9tyzxyljdju.apps.cloud.couchbase.com/pos
    continuous: true
    replicator-type: PUSH_AND_PULL
    reset-checkpoint: false
    websocket:
      timeout: 10000
      heartbeat: 15000
    listeners:
      status:
        max-size: 10000
        max-duration: 1m
      counter:
        max-size: 10000
        max-duration: 1m
    collections:
      photoClassification:
        documentIDs-filter:
        channels-filter:
    authenticator:
      username: HelloKitty
      password: HelloKitty1!
  local:
    database: db
    db-path: data
    download-path: tmpdb
    pre-built: false
    copy-db: false
    flush-previous-db: false
    auto-purge: true
    scope:
      name: scopePOS
      collections: photoClassification
  log:
    path: logs
    level: info
    max-size: 100000000
    rotation-count: 10
    plaintext: true